set_property PACKAGE_PIN Y18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN P20 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN C19 [get_ports {cs_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs_o[0]}]
set_property PACKAGE_PIN E19 [get_ports {cs_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs_o[1]}]
set_property PACKAGE_PIN D19 [get_ports {cs_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs_o[2]}]
set_property PACKAGE_PIN F18 [get_ports {cs_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs_o[3]}]
set_property PACKAGE_PIN E18 [get_ports {cs_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs_o[4]}]
set_property PACKAGE_PIN B20 [get_ports {cs_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs_o[5]}]
set_property PACKAGE_PIN A20 [get_ports {cs_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs_o[6]}]
set_property PACKAGE_PIN A18 [get_ports {cs_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs_o[7]}]

set_property PACKAGE_PIN E13 [get_ports {code[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {code[0]}]
set_property PACKAGE_PIN C15 [get_ports {code[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {code[1]}]
set_property PACKAGE_PIN C14 [get_ports {code[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {code[2]}]
set_property PACKAGE_PIN E17 [get_ports {code[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {code[3]}]
set_property PACKAGE_PIN F16 [get_ports {code[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {code[4]}]
set_property PACKAGE_PIN F14 [get_ports {code[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {code[5]}]
set_property PACKAGE_PIN F13 [get_ports {code[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {code[6]}]
set_property PACKAGE_PIN F15 [get_ports {code[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {code[7]}]

set_property PACKAGE_PIN K17 [get_ports {east[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {east[0]}]
set_property PACKAGE_PIN L13 [get_ports {west[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {west[0]}]
set_property PACKAGE_PIN M13 [get_ports {south[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {south[0]}]
set_property PACKAGE_PIN K14 [get_ports {north[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {north[0]}]

set_property PACKAGE_PIN K13 [get_ports {gnd}]
set_property IOSTANDARD LVCMOS33 [get_ports {gnd}]
set_property PACKAGE_PIN M20 [get_ports {gnd}]
set_property IOSTANDARD LVCMOS33 [get_ports {gnd}]
set_property PACKAGE_PIN N20 [get_ports {gnd}]
set_property IOSTANDARD LVCMOS33 [get_ports {gnd}]
set_property PACKAGE_PIN N19 [get_ports {gnd}]
set_property IOSTANDARD LVCMOS33 [get_ports {gnd}]



set_property PACKAGE_PIN M17 [get_ports {east[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {east[1]}]
set_property PACKAGE_PIN M16 [get_ports {west[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {west[1]}]
set_property PACKAGE_PIN M15 [get_ports {south[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {south[1]}]
set_property PACKAGE_PIN K16 [get_ports {north[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {north[1]}]

set_property PACKAGE_PIN L16 [get_ports {gnd}]
set_property IOSTANDARD LVCMOS33 [get_ports {gnd}]
set_property PACKAGE_PIN L15 [get_ports {gnd}]
set_property IOSTANDARD LVCMOS33 [get_ports {gnd}]
set_property PACKAGE_PIN L14 [get_ports {gnd}]
set_property IOSTANDARD LVCMOS33 [get_ports {gnd}]
set_property PACKAGE_PIN J17 [get_ports {gnd}]
set_property IOSTANDARD LVCMOS33 [get_ports {gnd}]


set_property PACKAGE_PIN F21 [get_ports {east[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {east[2]}]
set_property PACKAGE_PIN G22 [get_ports {west[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {west[2]}]
set_property PACKAGE_PIN G21 [get_ports {south[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {south[2]}]
set_property PACKAGE_PIN D21 [get_ports {north[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {north[2]}]

set_property PACKAGE_PIN E21 [get_ports {gnd}]
set_property IOSTANDARD LVCMOS33 [get_ports {gnd}]
set_property PACKAGE_PIN D22 [get_ports {gnd}]
set_property IOSTANDARD LVCMOS33 [get_ports {gnd}]
set_property PACKAGE_PIN E22 [get_ports {gnd}]
set_property IOSTANDARD LVCMOS33 [get_ports {gnd}]
set_property PACKAGE_PIN A21 [get_ports {gnd}]
set_property IOSTANDARD LVCMOS33 [get_ports {gnd}]
