# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = '《数字逻辑与计算机组成》实验'
copyright = '：深圳理工大学 - 算力微电子学院，2026 '
author = '黄夕祠，陈奕含'
release = '1.0'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

master_doc = 'index'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.

extensions = ['recommonmark',
  'sphinx_markdown_tables',
  'sphinx.ext.autosectionlabel'
]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:

source_suffix = ['.rst', 'rest', '.md']

# Add any paths that contain templates here, relative to this directory.

templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.

source_encoding = 'utf-8'
language = 'zh_CN'
html_search_language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.

exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".

html_static_path = ['_static']

html_extra_path = ['files']

html_css_files = ['custom.css']
html_js_files = ['copy-code.js', 'download-files.js']


def write_download_script(app, exception):
    """Embed download bytes so downloads also work on local file:// pages."""
    if exception is not None or app.builder.format != 'html':
        return

    import base64
    import json
    from pathlib import Path

    files = {
        name: base64.b64encode(
            (Path(app.srcdir) / 'lab2' / name).read_bytes()
        ).decode('ascii')
        for name in ('seg.v', 'seg_driver.v', 'shifter.xdc')
    }
    script = "const verilogDownloads = " + json.dumps(files) + ";\n" + r"""
document.addEventListener('click', (event) => {
    const link = event.target.closest('a[download]');
    if (!link) return;
    const filename = new URL(link.href).pathname.split('/').pop();
    if (!Object.prototype.hasOwnProperty.call(verilogDownloads, filename)) return;
    event.preventDefault();
    const bytes = Uint8Array.from(atob(verilogDownloads[filename]), c => c.charCodeAt(0));
    const url = URL.createObjectURL(new Blob([bytes], {type: 'application/octet-stream'}));
    const download = document.createElement('a');
    download.href = url;
    download.download = filename;
    document.body.appendChild(download);
    download.click();
    download.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
});
"""
    destination = Path(app.outdir) / '_static' / 'download-files.js'
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(script, encoding='utf-8')


def setup(app):
    app.connect('build-finished', write_download_script)

# Custom CSS
# margin-bottom: 0.5em;
# padding-bottom: 4px;
